[tool.kedro]
package_name = "basic_project"
project_name = "basic-project"
project_version = "0.18.0"

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_third_party = "kedro"
line_length = 88
multi_line_output = 3
use_parentheses = true

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/basic_project -ra"""

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
fail_under = 0
show_missing = true
